version: '3.8'

services:
  backend:
    env_file:
      - .env
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    container_name: auth_backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: rebuild
          path: package.json

  db:
    image: postgres:16.3-alpine3.18
    container_name: My_DB
    restart: unless-stopped
    volumes:
      # - .:/dev/shm
      - ~/db-data:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: true
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
          
volumes:
  db-data: