version: '3.8'

services:
  db:
    image: postgres:16.3-alpine3.18
    container_name: My_DB
    restart: unless-stopped
    volumes:
      # - .:/dev/shm
      - ~/db-data:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: true
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
          
volumes:
  db-data: